parser: babel-eslint
env:
  es6: true
  node: true
extends:
- prettier
- prettier/standard
plugins:
- prettier
- react
rules:
  prettier/prettier: error
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
      varsIgnorePattern: "^h$|^_"
  no-console:
  - error
  - allow:
    - warn
    - error
    - info
  no-undef: error
  no-const-assign: error
  no-class-assign: error
  constructor-super: error
  no-useless-escape: error
  react/jsx-uses-vars: error
